[package]
name = "whisper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
arboard = "3"
cpal = "0.15"
clap = { version = "4", features = ["derive"] }
crossbeam-channel = "0.5"
base64 = "0.22.1"
enigo = "0.1"
evdev = "0.12"
hound = "3"
once_cell = "1"
rdev = "0.5"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
urlencoding = "2"

[[bin]]
name = "whisper"
path = "main.rs"
